[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  'account-abstraction/=lib/account-abstraction/contracts/',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  'foundry-era-contracts/contracts=lib/foundry-era-contracts/src/system-contracts/contracts',
  'foundry-devops/contracts=lib/foundry-devops/src',
  'forge-std/=lib/forge-std/src/'
]

is-system = true
via-ir = true
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
